### PR TITLE
:bug: fix(51): Fixes #51 problem with asset copy

### LINKED ISSUE #51: No assets copied when template is specificed
There is a little glitch where if a template is specified as a string name of another npm package, topdoc does not correctly try to copy the assets from that package.

I will fix.

### PR DESCRIPTION
**Pull request by misterbrownlee**
Asset copy was failing if template was declared using the string name of another npm package

ISSUES CLOSED: #51 

HI @GarthDB I FIXED IT 😹

### CODE REVIEW

**Comment by misterbrownlee** [comment]
Maybe there's a test for this though... I keep forgetting about that.

**Comment by GarthDB** [comment]
Looks like 2 broken tests. Want to check them or would prefer I did it?

**Comment by misterbrownlee** [comment]
Let me... I have to learn somehow

**Comment by GarthDB** [comment]
Good luck!

**Comment by misterbrownlee** [comment]
I think unraveled a bit of the mess.  We are setting default options while configuring Commander, then passing more default options to config-attendent, plus a parser object that is essentially the state of commander.   I'm assuming we want command line to win if you put a redundant command line arg and config arg in both places?  Right now it looks like commander does win over config... the problem is commander's defaults _always_ win, even if you put something in config.  The only way to clobber a commander default is with an overriding command line arg.  That's a bit derp IMO. I have messed around with it and now have a pretty clean way to fix this. I just wanted to double check on who should win in a command line arg vs rc file.    I think it's pretty obvious .config should override a default.  And then once I fix the defaults that are unable to be overriden, I can fix this test  🎉

**Comment by misterbrownlee** [comment]
Also I apparently suck at using commitizen... sorry

**Comment by GarthDB** [comment]
Yeah rc trumps default and command line args trump rc.

**Comment by misterbrownlee** [comment]
I fixed it.  Let me know if you want me to walk you through all the changes?

**Comment by GarthDB** [comment]
I just started a code review on one line, I haven't done one before, not sure how it differs from line comments.

File: src/bin/index.js [hunk 1]
```diff
@@ -30,47 +33,74 @@ function _list(val) {
  *  Returns {String} when `val` is not a Boolean.
  *  Returns {Bool} when `val` is Boolean or Boolean String like 'false'.
  */
-function _valOrFalse(val) {
+function _booleanOrValue(val) {
   if (val === 'false' || !val) return false;
+  if (val === 'true') return true;
```
Comment (misterbrownlee) [inline src/bin/index.js]: oh... hmmm... brb

Comment (misterbrownlee) [inline src/bin/index.js]: doesn't the first line catch that?

**Comment by misterbrownlee** [comment]
@GarthDB were you wanting other changes to this, or to refactor or ?  I'm stuck using a local link of this until the bug fix parts of this are released.

**Comment by GarthDB** [comment]
I'll work on it today

**Comment by misterbrownlee** [comment]
🎉  🌮  🌮
